# Generated by Django 5.0.3 on 2024-04-04 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0003_usuario_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('AD', 'Administrador'), ('TR', 'Trabajador')], default='AD', max_length=2, verbose_name='Rol'),
        ),
    ]
